#!/usr/bin/env bash
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

echo "Updating /etc/hosts file"
{
    echo "127.0.0.2 localhost"
    echo "8.8.8.8 facebook.com"
} | sudo tee -a /etc/hosts